# Site
repository: puzzle29/konigkoudogbo.dev
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: König KOUDOGBO
title: Développeur web
email: koudogbokonig@gmail.com
website: konigkoudogbo.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: KKoudogbo
github_username:  puzzle29
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: könig-koudogbo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Apropos de moi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour, je suis König KOUDOGBO. En tant que passionné de la technologie, j'ai axé mes études dans cette direction et je suis déterminé à utiliser les dernières 
  <mark>technologies</mark> pour <mark>résoudre</mark> des <mark>problèmes</mark> et répondre à des besoins. Actuellement, je mets mes compétences en développement web au service de cette mission.

content:
  - title: Mes projets # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Plateforme de candidature à l'Ecole d'Ete sur l'Intelligence Artificielle
        link: eeia.bj
        # link_text: Plateforme de candidature à l'Ecole d'Ete sur l'Intelligence Artificielle
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          J'ai été honoré de travailler sur ce projet et d'avoir eu la chance d'en apprendre autant sur le développement web que sur la gestion.
        description: | # this will include new lines to allow paragraphs
          Cette plateforme a pour but de permettre à tous ceux qui sont passionnés par l'Intelligence Artificielle de candidater pour l’EEIA (Ecole d’été sur l’intelligence artificielle). L’EEIA est une formation à 75% pratique qui s’étend sur une durée de 4 semaines dans les vacances. Cette formation a pour principal objet l’initiation au domaine de l’Intelligence Artificielle.



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bénin Excellence
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Développeur web
        caption: Mars 2021 - Août 2022 | Cotonou (Bénin)
        quote: >
          Créer des plateformes web de candidature
        description: | # this will include new lines to allow paragraphs
            - Effectuer la maintenance des plateformes et corriger régulièrement les dysfonctionnements
            - Optimiser les performances de la plateforme et faire évoluer ses fonctionnalités
            - Formation des jeunes sur les bases du langage de programmation Python aucours des éditions précédentes de l’École d’Été sur l’Intelligence Artificielle (EEIA) de la Fondation Vallet
            - Animation des ateliers de travaux pratiques sur l’Intelligence Artificielle au cours des éditions précédentes de l’École d’Été sur l’Intelligence Artificielle (EEIA)
            - Gestion du réseau informatique et des serveurs de l’organisation
      
      - layout: left
        title: SerProWeb
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Stage - Développeur web
        caption: Août 2020 - décembre 2020 | Cotonou (Bénin)
        quote: >
          Développeur back-end
        description: | # this will include new lines to allow paragraphs
            - Analyser les différents besoins du client
            - Coder le back-end des sites web
            - Rédiger des documentations utilisateurs et techniques

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INSTITUT NATIONAL SUPERIEUR DE TECHNOLOGIE INDUSTRIELLE DE LOKOSSA, Lokossa (Bénin)
        caption: 2019
        sub_title: Licence Professionnelle en Informatique et Télécommunication
        quote: >
          Au cours de ce cursus, j'ai eu des bases solides en programmation plus particulièrement en développement web.
        description: | # this will include new lines to allow paragraphs
          - Cloud Computing
          - Big Data et Python
          - Programmation Web
          - Définition des modèles pour la prédiction des maladies cardio-vasculaires.

      - layout: left
        title: Université d'Aix-Marseille, Marseille
        caption: 2022 - 2023
        sub_title: Licence Informatique parcours Mathématiques-Informatique
        quote: >
          Au cours de ce cursus, j'ai eu des bases solides en programmation plus particulièrement en informatique thérorique.
        description: | # this will include new lines to allow paragraphs
          - Algorithmique avancée et théorie des graphes
          - Classification d'images de mer
          - Modélisation de la propagation d’une maladie contagieuse
          - Apprentissage Automatique
          - Correcteur orthographique


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
