# Site
repository: puzzle29/konigkoudogbo.dev
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: König KOUDOGBO
title: Développeur web
email: koudogbokonig@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: KKoudogbo
github_username:  puzzle29
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: könig-koudogbo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: A propos de moi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Je me présente, je suis König KOUDOGBO, un passionné de la technologie qui a orienté ses études dans cette voie. 
  Mon objectif est d'utiliser les dernières <mark>technologies</mark> pour <mark>résoudre</mark> des <mark>problèmes</mark> et répondre aux besoins de manière innovante. 
  
  Mon domaine de prédilection est le développement web, dans lequel j'ai acquis une expérience de 2 ans et eu la chance de travailler sur plusieurs projets réussis, 
  tels qu'une plateforme ayant déjà accueilli plus de 8000 utilisateurs. Bien que mes compétences soient principalement en développement back-end, je suis tout aussi à l'aise en 
  front-end. Actuellement, je suis familiarisé avec les langages <mark>PHP (Laravel + API)</mark> et <mark>Javascript (Vue Js)</mark>, et j'aime explorer de nouvelles librairies et frameworks pour diversifier mes 
  connaissances. Mon intérêt pour l'intelligence artificielle m'a également conduit à m'informer continuellement dans ce domaine, dans l'espoir d'appliquer cette expertise à la création de solutions innovantes.
  
content:
  - title: Mes projets # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Plateforme de candidature à l'EEIA
        # link: eeia.bj
        # link_text: Plateforme de candidature à l'Ecole d'Ete sur l'Intelligence Artificielle
        additional_links:
          - title:  EEIA
            # icon: fab fa-github
            url: eeia.beninexcellence.org
          - title:  EEIA-Junior
            # icon: fab fa-github
            url: eeia.beninexcellence.org
        quote: >
          Cette plateforme permet une dématérialisation du processus de candidature à l'EEIA.
        description: | # this will include new lines to allow paragraphs
          Cette plateforme a pour but de permettre à tous ceux qui sont passionnés par l'Intelligence Artificielle de candidater pour l’EEIA (Ecole d’été sur l’intelligence artificielle). L’EEIA est une formation à 75% pratique qui s’étend sur une durée de 4 semaines dans les vacances. Cette formation a pour principal objet l’initiation au domaine de l’Intelligence Artificielle.



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Bénin Excellence
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Développeur web
        caption: Mars 2021 - Août 2022 | Cotonou (Bénin)
        description: | # this will include new lines to allow paragraphs
            <ins>TLDR:</ins>
            - Création de plateformes web 
            - Correction des bugs et maintenance des plateformes 
            - Optimiser les performances des plateformes et faire évoluer ses fonctionnalités
            - Formation des jeunes sur les bases du langage de programmation Python au
            cours des éditions précédentes de l’[Ecole d'Ete sur l'Intelligence Artificielle (EEIA)](https://eeia.bj)
            de la [Fondation Vallet](https://fondationvallet.org)
            - Animation des ateliers de travaux pratiques sur l’Intelligence Artificielle au cours
            des éditions précédentes de l’École d’Été sur l’Intelligence Artificielle (EEIA)
            - Gestion du réseau informatique et des serveurs de l’organisation
            
            En tant que développeur web, j'ai eu la chance de travailler pour Bénin Excellence, de concevoir et de développer des plateformes pour la [Fondation Vallet](https://fondationvallet.org). Plus précisément, j'ai créé des plateformes de candidatures de bourse pour les écoles d'art en France dans le compte de la Fondation Vallet et pour l'[Ecole d'Ete sur l'Intelligence Artificielle (EEIA)](https:eeia.bj). Chacune de ces plateformes comprenait une interface d'administration avec des fonctionnalités spécifiques telles que le téléchargement des dossiers des élèves par établissement ou la consultation et l'évaluation des dossiers de candidats.

            En utilisant mes compétences en tant que développeur Back-end, j'ai développé ces plateformes en utilisant une architecture d'<mark>API</mark> et une application <mark>SPA</mark>(Single Page Application). Pour le Backend, j'ai utilisé <mark>Laravel</mark> et pour le front, j'ai utilisé <mark>Vue Js</mark>. J'ai également accordé une grande importance à la sécurité des API et j'ai amélioré autant que possible le temps de chargement des applications SPA.

            En tant que principal développeur sur ces projets, j'ai utilisé mes expériences précédentes pour respecter les meilleures pratiques, telles que l'utilisation de GitHub ou la création d'environnements de test avant le déploiement. Ces projets m'ont permis de renforcer mes compétences en développement, mais aussi de découvrir de nouveaux outils passionnants.

            En plus de mon rôle de développeur web, j’ai également été chargé de répondre aux questions techniques en tant que l'un des informaticiens de l’organisation comme la gestion des serveurs de messagerie. J’ai même eu l’occasion de modifier un portail captif pour empêcher certains appareils d’accéder à la connexion de l’organisation.

            Enfin, j'ai également été formateur en langage <mark>Python</mark> lors de l'EEIA et j'ai eu l'honneur d'encadrer un atelier pratique sur l'optimisation des pales d'un hélicoptère. Cette expérience m'a permis de rencontrer de nombreux experts qui m'ont transmis de précieuses connaissances sur l'<mark>Intelligence Artificielle</mark>.
      
      - layout: left
        title: SerProWeb
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Stage - Développeur web
        caption: Août 2020 - décembre 2020 | Cotonou (Bénin)
        description: | # this will include new lines to allow paragraphs
            <ins>TLDR:</ins>
            - Analyser les différents besoins du client
            - Coder le back-end des sites web
            - Rédiger des documentations utilisateurs et techniques

            Cette agence de développement web a été pour moi le début de ma carrière de développeur web. J'y ai appris certaines bonnes pratiques de développement et le travail en équipe. Je développais principalement en utilisant <mark>Laravel</mark> et <mark>Jquery</mark>. J'ai eu également l'opportunité de travailler sur des projets et d'être en relation directement avec les clients.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Université d'Aix-Marseille, Marseille
        caption: 2022 - 2023
        sub_title: Licence Informatique parcours Mathématiques-Informatique
        description: | # this will include new lines to allow paragraphs
          <ins>TLDR:</ins>
          - Algorithmique avancée et théorie des graphes
          - Classification d'images de mer _(TP)_
          - Modélisation de la propagation d’une maladie contagieuse _(TP)_
          - Apprentissage Automatique 
          - Correcteur orthographique _(TP)_

          Ce cursus m'a permis d'approfondir mes connaissances en informatique théorique et de développer mes compétences en travaillant sur des projets pratiques. J'ai ainsi pu maîtriser de nouveaux algorithmes et découvrir de nouveaux langages de programmation tels que <mark>Java</mark>.

          Au-delà de ces enseignements, j'ai particulièrement été marqué par l'apprentissage automatique, qui m'a permis de mieux comprendre les principes du <mark>Machine Learning</mark> et de me familiariser avec les termes spécifiques à ce domaine. Cette formation m'a également permis de prendre conscience de l'importance des mathématiques dans l'ingénierie informatique. J'ai ainsi travaillé en groupe sur un projet portant sur les permutations, pour lequel j'étais en charge du codage en JAVA.
      - layout: left
        title: INSTI, Lokossa (Bénin)
        caption: 2019
        sub_title: Licence Professionnelle en Informatique et Télécommunication
        description: | # this will include new lines to allow paragraphs
          <ins>TLDR:</ins>
          - Cloud Computing
          - Big Data et Python
          - Programmation Web
          - Définition des modèles pour la prédiction des maladies cardio-vasculaires _(Projet)_

          
          J'ai obtenu une licence professionnelle en Génie Électrique et Informatique Industrielle à 
          l'Institut National Superieur de Technologie Industrielle (INSTI), mon premier diplôme universitaire. 
          Cette formation m'a non seulement introduit à la programmation que j'ai appris à apprécier, mais m'a également initiée au monde professionnel.
          
          Ce cursus universitaire m'a permis d'acquérir une grande variété de compétences en électricité, électronique, ainsi qu'en informatique. J'ai pu ainsi découvrir l'intelligence artificielle et la programmation en <mark>Python</mark> à travers le Big Data. Cette formation m'a également initié au développement web.

          Mon intérêt pour l'intelligence artificielle m'a d'ailleurs poussé à faire des recherches et à soutenir mon projet de fin d'études sur la "Définition des modèles contextuels pour la prédiction des maladies cardio-vasculaires". Ce projet m'a permis d'explorer le domaine de l'intelligence artificielle et de faire de l'algorithmique avancée.

  - title: Mes Passe-temps Favoris
    layout: text
    content: | # this will include new lines to allow paragraphs
      Je m'intéresse beaucoup à la photographie, je ne rate par l'occasion d'immortaliser un moment ou de prendre en photo tout ce que je trouve particulier.
      
      J'aime également bouger mon corps à travers la danse. Je fais d'ailleurs actuellement la capoeira.
      
      En plus de cela, j'aime aussi me cultiver, je passe pas mal de temps sur les sujets de développement ou technologique de façon générale à travers la lecture et les vidéos.

  - title: Actions Sociales
    layout: text
    content: | # this will include new lines to allow paragraphs
      Je suis motivé(e) par l'envie de <mark>contribuer</mark> à la société et j'ai toujours cherché à être utile. Pendant mes années universitaires à l'INSTI (Bénin), j'ai participé activement au mouvement scout. Au-delà des animations organisées, j'ai eu l'occasion de participer à des actions de bénévolat, de dons, de sensibilisation et de sécurité. Cette expérience m'a appris de nombreuses valeurs, notamment la vie en communauté, le respect, la responsabilité et surtout la satisfaction de rendre les autres heureux.
      
      J'ai également apporté ma contribution à la sensibilisation pendant la pandémie de COVID-19 en participant à une formation proposée par l'ONG Welp. Mon engagement a été remarqué, ce qui m'a permis d'être nommé webmaster de l'association avec honneur. Cette expérience m'a appris que même les petites actions peuvent avoir un grand impact.
      
      En raison de ma préoccupation concernant les enjeux environnementaux, j'ai collaboré avec une amie pour proposer une solution visant à prévenir la pollution causée par les mégots de cigarette jetés sur le sol. Notre solution s'intitulait "Porte-Mégots" et consistait en la fabrication et en la distribution de cendriers portatifs. Grâce à cette initiative, j'ai eu la chance d'être sélectionné pour présenter notre solution lors du concours "DD EN TRANS’ : LE DÉVELOPPEMENT DURABLE EST INTERDISCIPLINAIRE" organisé par Aix-Marseille Université. Bien que notre projet n'ait pas remporté de prix, cette expérience a été enrichissante en termes de partage, de rencontre et de [bonne humeur](images/happy-me.JPG).



# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
